name: Update Tag

on:
  push:
    branches:
      - master

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: koirand/github-action-tag@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
