name: Update revision

on:
  push:
    branches:
      - develop

jobs:
  version-up:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: koirand/github-action-tag@master
      with:
        WHAT_TO_UPDATE: revision
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
