name: Update minor version

on:
  push:
    branches:
      - master

jobs:
  version-up:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: koirand/github-action-tag@master
      with:
        what_to_update: minor
      env:
        github_token: ${{ secrets.GITHUB_TOKEN }}
