name: Update major version

on:
  push:
    branches-ignore::
      - release
      - master

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: koirand/github-action-tag@master
      with:
        what-to-update: revision
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
